services:
  mysql-db:
    build: ./database
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend-service
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: myapp

  powerbi:
    build: ./powerbi
    container_name: powerbi-server
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

volumes:
  db-data:

